### ISSUE TITLE
Feat : The title of Eventify is not updated yet 

### ISSUE THREAD

**Issue by dheerajsingh01** [sandeshkolte/Campus_Event_App#16]
hey @sandeshkolte do assign this issue.
I update the title and update the logo of your application, if you have any logo you can provide me to do it.

**Comment by dheerajsingh01** [comment]
Don't forget to Assign this issue to me with levels like hacktoberfest and hactoberfest-accepted

**Comment by sandeshkolte** [comment]
We have specific team for the fullstack. Sorry, but we can't accept any changes from other members.
